environment: # max: 365*96
  grid_size: 16
  learn_policy: "independent_ppo"
  max_cycles: 384 # 96*4
  houses_per_node: 6
  climate_zone: 1
  hourly_timesteps: 4

train:
  epochs: 180
  show_evaluate_epoch: 100
  evaluate_epoch: 2




