wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1664956600.729385
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.13.2
      8:
      - 5
buildings_states_actions_file:
  desc: null
  value: ../envs/data/buildings_state_action_space.json
climate_zone:
  desc: null
  value: 1
data_path:
  desc: null
  value: ../envs/data/Climate_Zone_1
hourly_timesteps:
  desc: null
  value: 4
houses_per_node:
  desc: null
  value: 3
max_num_houses:
  desc: null
  value: null
model_name:
  desc: null
  value: 96agents
