environment: # max: 365*96
  grid_size: 16
  learn_policy: "RBC"
  max_cycles: 192 # 96*2
  houses_per_node: 2
  climate_zone: 1
  hourly_timesteps: 4

train:
  epochs: 360
  show_evaluate_epoch: 100
  evaluate_epoch: 2




